### ISSUE TITLE
Website Design Feedback

### ISSUE THREAD

**Issue by gdams** [CloudNativeJS/cloudnativejs.io#49]
Using this issue to track any website design feedback/improvements

**Comment by TreeHanh** [comment]
![cloudnative_redesign_black](https://user-images.githubusercontent.com/18586040/47227378-ad3ce280-d390-11e8-88ec-5c3b2e12f5b6.jpg)
![cloudnative_redesign_teal](https://user-images.githubusercontent.com/18586040/47227379-ad3ce280-d390-11e8-8555-53abbf510c55.jpg)
![cloudnative_redesign_blue](https://user-images.githubusercontent.com/18586040/47227380-ad3ce280-d390-11e8-9944-153688b1865d.jpg)

**Comment by tomleah** [comment]
Out of interest, does anyone have a suggestion on what would be the best way to create those multiple diagonals on the landing part of the design? a SVG as a background or some CSS tricks?

**Comment by TreeHanh** [comment]
Logo

![cloudnative_logo](https://user-images.githubusercontent.com/18586040/47237936-82618700-d3ae-11e8-92bf-4829822fd194.png)

**Comment by TreeHanh** [comment]
Redlines and assets for the homepage design
[CloudNative_Redlines_Assets.zip](https://github.com/CloudNativeJS/cloudnativejs.io/files/2511410/CloudNative_Redlines_Assets.zip)

**Comment by gdams** [comment]
closing as the PR got merged
